# Generated by Django 5.2.4 on 2025-07-30 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendanceclass',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.attendanceclass'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='admins.subject'),
        ),
        migrations.AddField(
            model_name='attendancetotal',
            name='subject',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='admins.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancetotal',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='admins.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancetotal',
            unique_together={('student', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('student', 'subject')},
        ),
    ]
