# Generated by Django 5.2.1 on 2025-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_change_cascade_to_restrict"),
    ]
