# Generated by Django 5.2.4 on 2025-07-30 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='dept',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='admins.dept'),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dept',
            name='id',
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dept',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='admins.dept'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False),
        ),
    ]
