# Generated by Django 5.2.4 on 2025-08-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_change_cascade_to_restrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
