# Generated by Django 5.2.4 on 2025-07-30 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_change_cascade_to_restrict'),
        ('students', '0003_change_cascade_to_restrict'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admins.class'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admins.subject'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teachers.assign'),
        ),
        migrations.AlterField(
            model_name='attendanceclass',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teachers.assign'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teachers.assign'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.studentsubject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='admins.dept'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
