# Generated by Django 5.2.1 on 2025-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0003_class_is_active"),
        ("teachers", "0002_change_cascade_to_restrict"),
    ]

    operations = [
        migrations.AddField(
            model_name="assign",
            name="academic_year",
            field=models.CharField(default="2024-2025", max_length=20),
        ),
        migrations.AddField(
            model_name="assign",
            name="semester",
            field=models.IntegerField(default=1),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="assign",
                    unique_together={
                        ("subject", "class_id", "teacher", "academic_year", "semester")
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'teachers_assign_unique_year_sem'
    ) THEN
        ALTER TABLE teachers_assign
        ADD CONSTRAINT teachers_assign_unique_year_sem
        UNIQUE (subject_id, class_id_id, teacher_id, academic_year, semester);
    END IF;
END $$;
"""
                    ),
                    reverse_sql=(
                        """
ALTER TABLE IF EXISTS teachers_assign
DROP CONSTRAINT IF EXISTS teachers_assign_unique_year_sem;
"""
                    ),
                ),
            ],
        ),
    ]
