# Generated by Django 5.2.1 on 2025-08-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0003_alter_assign_unique_together_assign_academic_year_and_more"),
    ]

    