# Generated by Django 5.2.1 on 2025-08-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_studentsubject_is_active"),
        ("teachers", "0004_assign_is_active"),
    ]

    operations = [
        # Cập nhật state để có trường mới, bỏ thao tác DB vì cột đã tồn tại
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="marks",
                    name="academic_year",
                    field=models.CharField(default="2024-2025", max_length=20),
                ),
                migrations.AddField(
                    model_name="marks",
                    name="semester",
                    field=models.IntegerField(default=1),
                ),
            ],
        ),
        # Tạo unique constraint mới
        migrations.AddConstraint(
            model_name="marks",
            constraint=models.UniqueConstraint(
                fields=("student_subject", "name", "academic_year", "semester"),
                name="marks_unique_student_name_year_sem",
            ),
        ),
    ]
